#! /bin/sh

# Start sxhkd : keybinding daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# Set wallpaper : nitrogen 
nitrogen --set-scaled /home/varshith/wallpaper/wallpaper.jpg

# Source pywal colours
# . "${HOME}/.cache/wal/colors.sh"

# Set border colours
# bspc config normal_border_color "$color15"
# bspc config active_border_color "$color2"
# bspc config focused_border_color "$color1"

# Set border width
bspc config border_width 5

# Set desktops
bspc monitor -d I II III IV V VI VII VIII IX X
